name: Continuous Integration (CI)

## Run CI jobs on all branches by default
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Java toolchain
        uses: actions/setup-java@v4 # v4.7.0
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Run unit tests
        run: ./gradlew test
      - name: Build and Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
